"""Exact Google Sheets contract produced by google-apps-script/Code.gs."""

TOTAL_TABLES = 12
TIME_ZONE = "Asia/Jakarta"
OPERATING_HOURS = tuple(range(12, 24)) + tuple(range(0, 3))

SHEET_NAMES = (
    "Transactions",
    "Billiard_Sessions",
    "FNB_Items",
    "Daily_Summary",
)

SHEET_COLUMNS = {
    "Transactions": (
        "Timestamp",
        "Business Date",
        "Revenue Date",
        "Invoice Number",
        "Transaction Type",
        "Table Number",
        "Cashier",
        "Payment Method",
        "Billiard Subtotal",
        "F&B Subtotal",
        "Subtotal",
        "Discount Name",
        "Discount Percent",
        "Discount Amount",
        "Grand Total",
        "Paid At",
        "Synced At",
    ),
    "Billiard_Sessions": (
        "Timestamp",
        "Business Date",
        "Revenue Date",
        "Paid At",
        "Invoice Number",
        "Session Number",
        "Table Number",
        "Package ID",
        "Package Name",
        "Pricing Mode",
        "Start Time",
        "End Time",
        "Duration Minutes",
        "Rate",
        "Session Subtotal",
        "Status",
    ),
    "FNB_Items": (
        "Timestamp",
        "Business Date",
        "Revenue Date",
        "Paid At",
        "Invoice Number",
        "Transaction Type",
        "Table Number",
        "Menu ID",
        "Menu Name",
        "Quantity",
        "Unit Price",
        "Line Total",
    ),
    "Daily_Summary": (
        "Revenue Date",
        "Invoice Count",
        "Billiard Revenue",
        "F&B Revenue",
        "Discount Total",
        "Grand Revenue",
        "Cash",
        "QRIS",
        "Card",
        "Other",
        "Last Updated",
    ),
}

# Exact external-to-canonical mapping. External names must stay synchronized with
# BBL_SHEETS in google-apps-script/Code.gs; internal names are the analytics API.
SHEET_COLUMN_MAPS = {
    "Transactions": {
        "Timestamp": "timestamp",
        "Business Date": "business_date",
        "Revenue Date": "revenue_date",
        "Invoice Number": "invoice_number",
        "Transaction Type": "transaction_type",
        "Table Number": "table_number",
        "Cashier": "cashier",
        "Payment Method": "payment_method",
        "Billiard Subtotal": "billiard_revenue",
        "F&B Subtotal": "fnb_revenue",
        "Subtotal": "subtotal",
        "Discount Name": "discount_name",
        "Discount Percent": "discount_percent",
        "Discount Amount": "discount_amount",
        "Grand Total": "grand_total",
        "Paid At": "paid_at",
        "Synced At": "synced_at",
    },
    "Billiard_Sessions": {
        "Timestamp": "timestamp",
        "Business Date": "business_date",
        "Revenue Date": "revenue_date",
        "Paid At": "paid_at",
        "Invoice Number": "invoice_number",
        "Session Number": "session_number",
        "Table Number": "table_number",
        "Package ID": "package_id",
        "Package Name": "package_name",
        "Pricing Mode": "pricing_mode",
        "Start Time": "start_time",
        "End Time": "end_time",
        "Duration Minutes": "duration_minutes",
        "Rate": "rate",
        "Session Subtotal": "session_subtotal",
        "Status": "status",
    },
    "FNB_Items": {
        "Timestamp": "timestamp",
        "Business Date": "business_date",
        "Revenue Date": "revenue_date",
        "Paid At": "paid_at",
        "Invoice Number": "invoice_number",
        "Transaction Type": "transaction_type",
        "Table Number": "table_number",
        "Menu ID": "menu_id",
        "Menu Name": "menu_name",
        "Quantity": "quantity",
        "Unit Price": "unit_price",
        "Line Total": "line_total",
    },
    "Daily_Summary": {
        "Revenue Date": "revenue_date",
        "Invoice Count": "invoice_count",
        "Billiard Revenue": "billiard_revenue",
        "F&B Revenue": "fnb_revenue",
        "Discount Total": "discount_total",
        "Grand Revenue": "grand_revenue",
        "Cash": "cash",
        "QRIS": "qris",
        "Card": "card",
        "Other": "other",
        "Last Updated": "last_updated",
    },
}

SHEET_FINANCIAL_COLUMNS = {
    "Transactions": (
        "Billiard Subtotal",
        "F&B Subtotal",
        "Subtotal",
        "Discount Amount",
        "Grand Total",
    ),
    "Billiard_Sessions": ("Rate", "Session Subtotal"),
    "FNB_Items": ("Unit Price", "Line Total"),
    "Daily_Summary": (
        "Billiard Revenue",
        "F&B Revenue",
        "Discount Total",
        "Grand Revenue",
        "Cash",
        "QRIS",
        "Card",
        "Other",
    ),
}

TRANSACTION_TYPES = ("TABLE", "STANDALONE_FNB")
PAID_STATUSES = ("PAID", "COMPLETED", "CLOSED")
